on: [push]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'TokiTheToki'
          reponame: 'the-museum-of-us'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
  deploytonekoweb:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    needs: build_vue
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: 'the-museum-of-us.nekoweb.org'
          nekoweb-username: 'the-museum-of-us'
          directory: '/'